dist: trusty
sudo: false
language: node_js
cache:
  - bundler
  - yarn
node_js:
  - "7.10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
  - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
  - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
  - unzip out/chrome-linux.zip -d out
before_script:
  - export CHROME_CANARY_BIN=$PWD/out/chrome-linux/chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn test -- --browsers=ChromeCanaryHeadless
after_success:
  - bash <(curl -s https://codecov.io/bash)
