// Reference to Easing function(s).
// https://github.com/component/ease
// https://github.com/tweenjs/tween.js
module.exports = {
    linear: require('./linear'),
    inQuad: require('./inQuad'),
    outQuad: require('./outQuad'),
    inOutQuad: require('./inOutQuad'),
    inCube: require('./inCube'),
    outCube: require('./outCube'),
    inOutCube: require('./inOutCube'),
    inQuart: require('./inQuart'),
    outQuart: require('./outQuart'),
    inOutQuart: require('./inOutQuart'),
    inQunit: require('./inQunit'),
    outQunit: require('./outQunit'),
    inOutQunit: require('./inOutQunit'),
    inSine: require('./inSine'),
    outSine: require('./outSine'),
    inOutSine: require('./inOutSine'),
    inExpo: require('./inExpo'),
    outExpo: require('./outExpo'),
    inOutExpo: require('./inOutExpo'),
    inCirc: require('./inCirc'),
    outCirc: require('./outCirc'),
    inOutCirc: require('./inOutCirc'),
    inBack: require('./inBack'),
    outBack: require('./outBack'),
    inOutBack: require('./inOutBack'),
    inBounce: require('./inBounce'),
    outBounce: require('./outBounce'),
    inOutBounce: require('./inOutBounce'),
    inElastic: require('./inElastic'),
    outElastic: require('./outElastic'),
    inOutElastic: require('./inOutElastic')
};
